### ISSUE TITLE
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe.

### ISSUE THREAD

**Issue by kolotev** [kottenator/settings-overrider#2]
Hello Rostyslav,

Any chance you can correct the following issue?

python3.7/site-packages/settings_overrider.py:23: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.

Thank you.

**Comment by kottenator** [comment]
Hi! Sorry, I'm super busy at my current job, almost no time for my side projects :( I'd appreciate if you or somebody else could create a pull-request that fixes this warning. I'd gladly review & eventually approve / merge it.

**Comment by kottenator** [comment]
@kolotev new version 1.0.0 uploaded to PyPI now.

**Comment by kolotev** [comment]
Dmitry & Rostyslav, thank you very much both.
